src/pages/editor-page/canvas/table-node-field.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field.tsx
- Issue #23: Introduced a primary key indicator on the table canvas to mark fields designated as primary keys.
- Issue #26: Added logic to enforce the unique attribute when toggling the primary key status on fields
This PR improves the user experience by visually indicating primary keys and maintaining schema integrity through proper attribute enforcement.
=> Enhance Table Canvas with Primary Key Indicator and Unique Attribute Enforcement upon PrimaryKey toggle

src/pages/examples-page/examples-page.tsx
Example page is not responsive with mobile few.
In case of mobile, I added center alignment of the titles and adjusted the padding x.
=> Fix examples page on mobile

src/pages/editor-page/side-panel/list-item-header-button/relationship-list-item-header-button.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-index/table-index.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-list-item-content.tsx
Possibly closes #21 
Used asChild prop wherever possible to evade use of button tag and remove any nesting
In case of Tooltip + Toggle combination using asChild is causing conflict between the data-states so the toggle is wrapped in span to seperate them
=> Fixed validateDOMNesting warning

src/dialogs/create-diagram-dialog/create-diagram-dialog.tsx
Fix for https://github.com/chartdb/chartdb/issues/25
=> Responsive - Adjust the "create new diagram" dialog size and margins

src/pages/editor-page/canvas/table-node-field.tsx, src/pages/editor-page/canvas/table-node.tsx
Hi, Severin from @tremorlabs here :)
Just found and fixed a small visual inconsistency. The `table-node` and `table-node-field` had a small gap in the corners because the rounded utility `lg` added too much radius. I replaced it with a custom value, closing the gap.
=> fix: rounded table node

src/pages/editor-page/canvas/table-node.tsx
PR fixes table name overflow out of the table view #51
=> fix: fix table name overflow 

src/context/scroll-context/scroll-context.tsx, src/context/scroll-context/scroll-provider.tsx, src/hooks/use-scroll-action.ts, src/i18n/locales/en.ts, src/i18n/locales/es.ts, src/pages/editor-page/canvas/canvas.tsx, src/pages/editor-page/top-navbar/top-navbar.tsx, src/router.tsx
It was not possible to zoom in or out with a mouse scroll in the grid because the panning was activated. 
Removed it to enable zoom on mouse scroll
=> fix: zoom in/out on scroll instead of panning

src/pages/editor-page/canvas/table-node/table-node-field.tsx, src/pages/editor-page/canvas/table-node/table-node.tsx
PR implements logic to restrict relationship handle on views.
fixes https://github.com/chartdb/chartdb/issues/14
Changelog:
1. Adds a conditional logic in `TableNodeField` component to check if the table `isView` true/false.
=> fix: restrict relationship handle  on views

src/pages/editor-page/side-panel/side-panel.tsx
2 things: 
1. zoom out to fit smoothly when filter schemas 
2. remove the clear functionality and put it to be the same as the tables/relationships functionality
=> Deal with zoom when filtering schemas

src/pages/examples-page/example-card.tsx
Currently, there is a UI overflow on the [https://app.chartdb.io/examples](https://app.chartdb.io/examples) page.
=> Fix UI overflow on "examples" page

src/i18n/locales/de.ts
This PR adds German translations for several previously untranslated UI fields in the `de.ts` file, including:
- Show/Hide Dependencies
- Copy to Clipboard
- Export Image Dialog options
- Dependency section
- Check Script Result
- Updated `de.ts` with new German translations.
- Ensured consistency with existing translations.
=> fix(i18n): Add missing German translations

src/components/select-box/select-box.tsx
Make SelectBox focusable with `tab` and on key press `space` it open the dropdown
Context: Allow to enter column name and type without leaving our keyboard
https://github.com/user-attachments/assets/a1d3c8e9-b9e1-405c-af3e-b042886215de
=> styles(select-box): allow using tab & space to show choices

README.md
Add section for running Docker container locally direct from GitHub's Container Registry image as published by project's GitHub Actions workflow. 
During discussion in discord, it was revealed that there are container images published and this extra snippet shows a way to leverage them.
=> Update Docker Instructions in README.md

src/pages/editor-page/top-navbar/last-saved.tsx
In the top-navbar, the message indicating the date the diagram was last saved at is not translated. In English, we can see "Last saved 2 days ago". In Russian: "Последнее сохранение 2 days go".
I updated last-saved.tsx because it was straightforward, but it's not ideal because we have to maintain 2 locale lists: one here and the second in i18n.ts.
=> fix(Last Saved): Translate the "last saved" relative date message

src/context/chartdb-context/chartdb-provider.tsx, src/context/storage-context/storage-provider.tsx, src/lib/domain/db-table.ts, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-header/table-list-item-header.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list.tsx
This PR solves the following issue #393.
Reorder tables.
Mechanism:
1) When creating a new table, the `order` parameter is assigned the value `9999`.
2) When moving any table to a new position, all other tables change their index depending on the moved table.
The following functions have been tested:
1) Exporting the database to a JSON file
2) Importing a database from a JSON file
Preview:
=> feat(side-panel): Add functionality of order tables by drag & drop

src/lib/data/data-types/mariadb-data-types.ts
Madiadb is missing the UUID data type ([https://mariadb.com/kb/en/uuid-data-type/](https://mariadb.com/kb/en/uuid-data-type/)). I simply added it in `src/lib/data/data-types/mariadb-data-types.ts`
=> feat(mariadb): Add uuid data type

src/context/local-config-context/local-config-context.tsx, src/context/local-config-context/local-config-provider.tsx, src/i18n/locales/ar.ts, src/i18n/locales/bn.ts, src/i18n/locales/de.ts, src/i18n/locales/en.ts, src/i18n/locales/es.ts, src/i18n/locales/fr.ts, src/i18n/locales/gu.ts, src/i18n/locales/hi.ts, src/i18n/locales/id_ID.ts, src/i18n/locales/ja.ts, src/i18n/locales/ko_KR.ts, src/i18n/locales/mr.ts, src/i18n/locales/ne.ts, src/i18n/locales/pt_BR.ts, src/i18n/locales/ru.ts, src/i18n/locales/te.ts, src/i18n/locales/tr.ts, src/i18n/locales/uk.ts, src/i18n/locales/vi.ts, src/i18n/locales/zh_CN.ts, src/i18n/locales/zh_TW.ts, src/pages/editor-page/canvas/canvas.tsx, src/pages/editor-page/top-navbar/top-navbar.tsx
This PR fixes #496
This pull request adds functionality to toggle the visibility of the MiniMap on the canvas via the "View" menu.
- Added `showMiniMapOnCanvas` and `setShowMiniMapOnCanvas` to the `LocalConfigContext` and `LocalConfigProvider`.
- Used `localStorage` to persist the MiniMap visibility setting across sessions.
- Updated the `Canvas` component to conditionally render the MiniMap based on the `showMiniMapOnCanvas` state.
- Added a new menu item to the "View" menu for toggling the MiniMap.
- Added English translations for "Show MiniMap" and "Hide MiniMap" in the `en.ts` file.
- **Note:** I can add translations for other languages using online sources, but they may not be entirely accurate. I recommend having specialized contributors handle these translations for better quality …
=> feat(view-menu): add toggle for mini map visibility (#496)

src/context/export-image-context/export-image-provider.tsx
Problem:
There was an error importing CSS rules while downloading the image. The html-to-image package was attempting to import fonts from [Google Fonts](https://fonts.googleapis.com/).
Solution:
I added the configuration skipFonts: true to the toPng function. This resolved the issue. In the resulting image, there were no font-related problems. The fonts in the image matched those in the HTML. It seems the image doesn’t actually require those fonts, but the package tries to download them anyway.
=> fix(Image Export): importing css rules error while download image

Dockerfile, README.md, default.conf.template, entrypoint.sh, src/lib/data/export-metadata/export-sql-script.ts, src/lib/env.ts
This PR adds support for using custom OpenAI-compatible inference servers (like vLLM) as an alternative to the OpenAI API. This allows users to run ChartDB with their own inference servers and models.
- Added support for custom API endpoints via `OPENAI_API_ENDPOINT` environment variable
- Added support for custom model names via `LLM_MODEL_NAME` environment variable
- Updated configuration to work with either the original OpenAI API key OR custom endpoint setup
- Updated documentation to reflect new configuration options
- Added proper error handling for custom endpoint configurations
Tested with:
- vLLM server running Qwen/Qwen2.5-32B-Instruct-AWQ
- Verified SQL generation works with custom endpoint
- Verified build process with both OpenAI and custom endpoint configurations
- Tested …
=> feat(docker image): add support for custom inference servers

.github/workflows/publish.yaml
I was looking for a way to run ChartDB on a Raspberry Pi, saw issue #608, and decided to create a PR to solve the problem. I intentionally kept the scope small. If you would like other architectures, feel free to add them in later.
=> ci: support multi-arch build and publish

src/context/export-image-context/export-image-context.tsx, src/context/export-image-context/export-image-provider.tsx, src/dialogs/export-image-dialog/export-image-dialog.tsx, src/i18n/locales/ar.ts, src/i18n/locales/bn.ts, src/i18n/locales/de.ts, src/i18n/locales/en.ts, src/i18n/locales/es.ts, src/i18n/locales/fr.ts, src/i18n/locales/gu.ts, src/i18n/locales/hi.ts, src/i18n/locales/id_ID.ts, src/i18n/locales/ja.ts, src/i18n/locales/ko_KR.ts, src/i18n/locales/mr.ts, src/i18n/locales/ne.ts, src/i18n/locales/pt_BR.ts, src/i18n/locales/ru.ts, src/i18n/locales/te.ts, src/i18n/locales/tr.ts, src/i18n/locales/uk.ts, src/i18n/locales/vi.ts, src/i18n/locales/zh_CN.ts, src/i18n/locales/zh_TW.ts, src/pages/editor-page/top-navbar/menu/menu.tsx
This PR adds additional image export settings:
pattern - toggles the background dot pattern
transparent - background transparency
watermark - presence of watermark
I am sorry, I created the localization only for en.
=> feat(image-export): add transparent and pattern export image toggles

src/lib/domain/db-table.ts, src/pages/editor-page/canvas/canvas-utils.ts, src/pages/editor-page/canvas/canvas.tsx, src/pages/editor-page/canvas/table-node/table-node.tsx
1. Store is expanded
2. Reorder based on tables size
https://github.com/user-attachments/assets/67711113-b20f-48e6-928d-fdfc7186fd74
=> fix(expanded-table): persist expanded state across renders

src/context/chartdb-context/chartdb-context.tsx, src/context/chartdb-context/chartdb-provider.tsx, src/context/diagram-filter-context/diagram-filter-provider.tsx, src/i18n/locales/ar.ts, src/i18n/locales/bn.ts, src/i18n/locales/de.ts, src/i18n/locales/en.ts, src/i18n/locales/es.ts, src/i18n/locales/fr.ts, src/i18n/locales/gu.ts, src/i18n/locales/hi.ts, src/i18n/locales/hr.ts, src/i18n/locales/id_ID.ts, src/i18n/locales/ja.ts, src/i18n/locales/ko_KR.ts, src/i18n/locales/mr.ts, src/i18n/locales/ne.ts, src/i18n/locales/pt_BR.ts, src/i18n/locales/ru.ts, src/i18n/locales/te.ts, src/i18n/locales/tr.ts, src/i18n/locales/uk.ts, src/i18n/locales/vi.ts, src/i18n/locales/zh_CN.ts, src/i18n/locales/zh_TW.ts, src/lib/data/export-metadata/export-per-type/postgresql.ts, src/lib/domain/db-index.ts, src/pages/editor-page/canvas/canvas-filter/canvas-filter.tsx, src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-index/table-index.tsx
1. PostgreSQL Hash Index Support:
- Added index type property to the DBIndex model
- Extended UI to show index type dropdown for PostgreSQL databases
- Implemented proper SQL export with USING HASH clause
2. Single Field Constraint for Hash Indexes:
- When hash index type is selected, only one field can be selected
- If user tries to select another field, it replaces the current selection
- When switching from B-tree to Hash with multiple fields selected, it automatically keeps only the first field
- The UI shows "(single column only)" label for Hash index type
=> feat(postgres): add support hash index types

.github/workflows/cla.yaml
The CLA action does not need contents: write permission. Limit it to read for security.
=> fix(cla): Harden action
