chartdb/chartdb

Dockerfile
vite.config.ts

Add Docker image release

---

src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field.tsx

When collapsed field isn't visible and I've added tooltip to show the type.

Add tooltip to field type

---

package-lock.json
package.json
src/components/drawer/drawer.tsx
src/context/layout-context/layout-context.tsx
src/context/layout-context/layout-provider.tsx
src/pages/editor-page/canvas/canvas.tsx
src/pages/editor-page/editor-page.tsx

https://github.com/chartdb/chartdb/issues/29

add drawer to side panel on mobile

---

src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field.tsx

https://github.com/chartdb/chartdb/issues/63

Add tooltip for table name in the side panel

---

src/index.css
src/pages/editor-page/canvas/canvas.tsx
src/pages/editor-page/canvas/table-node.tsx

fix https://github.com/chartdb/chartdb/issues/61

expand and shrink table

---

src/components/combobox/combobox.tsx

TSIA.
Fixes chartdb/chartdb#80

Make search case insensitive

---

.dockerignore
Dockerfile
README.md

closes: https://github.com/chartdb/chartdb/issues/70

feat: optimize and improve dockerfile

---

README.md

adding logos for Supabase + TimescaleDB

chore: update README.md add indication we support Supbadse + TimescaleDB

---

src/pages/editor-page/side-panel/tables-section/tables-section.tsx

Added tooltip to collapse button. Resolves https://github.com/chartdb/chartdb/issues/137

Added tooltip to collapse button

---

src/pages/editor-page/canvas/table-node-field.tsx
src/pages/editor-page/canvas/table-node.tsx

Hey guys, 
I changed the colors. Give it a look. I think it looks good. It's related to #154.

Highlight fields when selecting a relationship on canvas

---

src/pages/editor-page/canvas/table-node-field.tsx

Fix https://github.com/chartdb/chartdb/issues/172

fix column names overflow

---

src/context/chartdb-context/chartdb-context.tsx
src/context/chartdb-context/chartdb-provider.tsx
src/pages/editor-page/canvas/canvas.tsx
src/pages/editor-page/canvas/table-node.tsx
src/pages/editor-page/side-panel/tables-section/table-list/table-list.tsx
src/pages/editor-page/side-panel/tables-section/tables-section.tsx

when creating new table it should:
1. be created in the current viewport where the user is looking 
2. be opened in the side panel in edit mode + scroll to it

Fix create new table 

---

src/lib/data/import-metadata/scripts/sqlite-script.ts

fix: :bug: pk_column changed to column in sqlite

---

src/i18n/i18n.ts
src/i18n/locales/fr.ts
src/pages/editor-page/top-navbar/top-navbar.tsx

I18n : added French Translation

---

src/i18n/i18n.ts
src/i18n/locales/de.ts
src/pages/editor-page/top-navbar/top-navbar.tsx

I18n : added German Translation

---

src/i18n/i18n.ts
src/i18n/locales/ja.ts
src/pages/editor-page/top-navbar/top-navbar.tsx

Added a new language for translation!

feat: added japanese language translation

---

src/i18n/locales/fr.ts

Added translations following fix(#226), related of missing translations.

(i18n): Add [FR] translation of missing fields

---

src/components/zoomable-image/zoomable-image.tsx
src/dialogs/common/import-database/import-database.tsx
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/hi.ts
src/i18n/locales/ja.ts
src/lib/data/import-metadata/utils.ts
src/lib/domain/db-relationship.ts
src/lib/domain/db-schema.ts
src/lib/utils.ts

We aim to assist pgAdmin users, and others, who encounter issues with broken JSON when copying it from their client.

fix broken import json for pgAdmin

---

src/i18n/i18n.ts
src/i18n/locales/uk.ts
src/pages/editor-page/top-navbar/top-navbar.tsx

added Ukrainian language. I don't know what kind of service it is, but I just helped with the translation into my native language

Add uk language

---

src/i18n/i18n.ts
src/i18n/locales/ko_KR.ts

chore(i18n): add korean

---

Dockerfile
README.md

fix: support openai key in docker build

---

src/globals.css
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/hi.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/uk.ts
src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-header/table-list-item-header.tsx
src/pages/editor-page/top-navbar/diagram-name.tsx
src/pages/editor-page/top-navbar/top-navbar.tsx

- Add direct click-to-edit on title names
- Fix event propagation conflicts
- Ensure consistent edit behavior between click and button triggers
Improves usability by allowing users to click directly on title names to edit them

chore(editable titles): improve title name edit interaction

---

src/i18n/i18n.ts
src/i18n/locales/ru.ts

Assigning me to original PR didn't help, probably because @kaleaditya779 didn't give me rights to commit to his fork, so I created mine, resolved merge conflicts, tested locally and added few more polishing changes.
This PR obsoletes https://github.com/chartdb/chartdb/pull/271

(i18n): Added Russian language V2

---

src/i18n/locales/es.ts

Adds translations that were pending on the ES (Spanish) locale

Adds missing spanish translations

---

src/i18n/i18n.ts
src/i18n/locales/zh_CN.ts

feat #130 : Add simplified chinese

feat: Add simplified chinese

---

CONTRIBUTING.md

PR adjusts the `CONTRIBUTING.md` to reference the correct license file.

docs: update license reference

---

package-lock.json
package.json
src/components/select-box/select-box.tsx
src/i18n/i18n.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/hi.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/uk.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/i18n/types.ts
src/pages/editor-page/top-navbar/language-nav/language-nav.tsx
src/pages/editor-page/top-navbar/top-navbar.tsx

fix(i18n): change language keeps selected language also after refreshing the page

---

src/i18n/locales/ko_KR.ts

Translation of strings added after v1.0.0

fix(i18n): update korean for 1.2.0

---

src/i18n/i18n.ts
src/i18n/locales/gu.ts

**Gujarati Language Support**
- Added translations for the application's user interface strings in Gujarati.
- Translations include dialogs, tooltips, navigation labels, error messages, and context menus.
- Language Metadata
**Introduced Gujarati language metadata (gu), including name and native name for proper recognition in the app's language settings.**
**Consistency and Accuracy**
Ensured all translations maintain contextual accuracy and align with the application's terminology.

Translating to gujarati language good first issue #130

---

src/i18n/i18n.ts
src/i18n/locales/vi.ts

This PR adds Vietnamese translations.

feat(i18n): add Vietnamese translations

---

src/i18n/locales/id_ID.ts

Complete TODO for Indonesian translation

feat(i18n): translate share and dialog sections in Indonesian locale 

---

src/i18n/locales/ar.ts

This PR fixes #508. 
I fixed the Arabic translations in the application by making edits to some formatting issues. This pull request improves the application's usability for Arabic-speaking users. Menus, dialogs, tooltips, alerts, and other parts of the app now display correctly in Arabic, providing a complete and accurate experience.

fix(i18n): translation/Arabic

---

package-lock.json
package.json
src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/pages/editor-page/side-panel/tables-section/tables-section.tsx

fix(filter-tables) show clean filter if no-results

---

src/pages/editor-page/canvas/table-node/table-node-field.tsx
src/pages/editor-page/canvas/table-node/table-node.tsx
src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-header/table-list-item-header.tsx

fix(canvas edit): add option to edit names in canvas

---

src/dialogs/open-diagram-dialog/open-diagram-dialog.tsx
src/hooks/use-debounce.ts

fix(open-diagram): add arrow keys navigation in open diagram dialog

---

src/pages/editor-page/side-panel/tables-section/tables-section.tsx

fix(dbml-editor): add shortcuts to dbml and filter: #534

---

src/i18n/locales/uk.ts

Minor improvements of Ukrainian translation.

fix(i18n): fix Ukrainian

---

src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
src/globals.css
src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts

feat(dbml-import): add error highlighting for dbml imports

---

src/lib/data/import-metadata/utils.ts

Fixing issues with the JSON cleanups.

fix(import-query): improve the cleanup for messy json input

---

src/pages/editor-page/side-panel/relationships-section/relationship-list/relationship-list-item/relationship-list-item-content/relationship-list-item-content.tsx

fix(realtionships-fk): add the schema to source/target tables

---

src/lib/dbml-import.ts

https://github.com/user-attachments/assets/4a9e6d47-1e70-4966-917b-854ead2ea4da

fix(import dbml): add import for indexes

---

src/context/dialog-context/dialog-context.tsx
src/context/dialog-context/dialog-provider.tsx
src/dialogs/create-relationship-dialog/create-relationship-dialog.tsx
src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/pages/editor-page/canvas/table-node/table-node-context-menu.tsx
src/pages/editor-page/canvas/table-node/table-node-field.tsx

https://github.com/user-attachments/assets/c737b7ef-1dac-45f0-a47f-e9dbc1c55044

fix(canvas): add right-click option to create relationships

---

src/dialogs/common/import-database/import-database.tsx
src/dialogs/common/import-database/ssms-info/ssms-info.tsx

https://github.com/user-attachments/assets/f9d080ea-9c33-41eb-9c42-21691a421603

fix(sqlserver-import): open ssms guide when max chars

---

src/lib/data/import-metadata/scripts/sqlserver-script.ts

fix(mssql-import): improve script readability by adding edition comment

---

src/context/dialog-context/dialog-context.tsx
src/context/dialog-context/dialog-provider.tsx
src/dialogs/create-diagram-dialog/create-diagram-dialog.tsx
src/dialogs/import-dbml-dialog/import-dbml-dialog.tsx
src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts

https://github.com/user-attachments/assets/30bce0da-2007-48b7-9df5-b1ae7df37845

fix(empty-state): show diff buttons on import-dbml when triggered by empty

---

src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/pages/editor-page/top-navbar/menu/menu.tsx

**3 changes:** 
1. ![image](https://github.com/user-attachments/assets/7013759d-bb4a-4100-9600-758bbd0bff0f)
2. ![image](https://github.com/user-attachments/assets/bef2bdbe-da0d-43c9-a70d-d7de7b341b3d)
3. ![image](https://github.com/user-attachments/assets/f93b9e8d-240e-4f63-8c84-c029b218520e)

fix(menu-backup): update export to be backup

---

src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/pages/editor-page/top-navbar/menu/menu.tsx

feat(add-docs): add link to ChartDB documentation

---

src/lib/data/export-metadata/export-sql-script.ts

This PR addresses issues with environment variable handling and configuration initialization for custom OpenAI endpoint API requests. Specifically, it ensures:
- **Proper Model Name Fallback:**
- Uses `??` (nullish coalescing) instead of `||` to prevent unintended fallback when `LLM_MODEL_NAME` is an empty string.
- Now correctly prioritizes `window.env.LLM_MODEL_NAME`, then `LLM_MODEL_NAME`, and finally defaults to `'gpt-4o-mini-2024-07-18'`.
- **Consistent API Key Handling:**
- Ensures `apiKey` is properly assigned in both cases (`useCustomEndpoint` or not).
- Removes hardcoded API key (`'sk-xxx'`) for security reasons.
- Fixed model name fallback using `??`.
- Standardized `config` assignment to avoid redundancy.
- Removed unnecessary hardcoded API key in `useCustomEndpoint` mode.
- …

fix(docker config): Environment Variable Handling and Configuration Logic

---

src/context/keyboard-shortcuts-context/keyboard-shortcuts.ts
src/context/theme-context/theme-provider.tsx
src/pages/editor-page/top-navbar/menu/menu.tsx

fix(shorcuts): add shortcut to toggle the theme

---

src/lib/data/export-metadata/export-per-type/sqlite.ts
src/lib/data/export-metadata/export-sql-script.ts

fix(export-sql): move from AI sql-export for sqlite to deterministic script

---

src/components/code-snippet/code-snippet.tsx
src/dialogs/common/import-database/import-database.tsx
src/dialogs/common/import-database/instructions-section/instructions/smart-query-instructions.tsx
src/lib/data/import-metadata/scripts/minimize-script.ts

@guyb1 still having issue when component mount for the first time. pls take a look when you can

fix(import): display query result formatted

---

src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx

fix(dbml-editor): remove invalid fields before showing DBML + warning

---

src/components/code-snippet/code-snippet.tsx
src/lib/data/export-metadata/export-sql-script.ts
src/pages/editor-page/side-panel/tables-section/table-dbml/table-dbml.tsx

@guyb1 ->its include also the changes in #686 
closed the 686

fix(dbml-editor): add inline refs mode + fix issues with DBML syntax

---

src/pages/editor-page/editor-sidebar/editor-sidebar.tsx
src/pages/editor-page/top-navbar/menu/menu.tsx

fix(dependencies): hide icon when diagram has no dependencies

---

src/dialogs/common/import-database/import-database.tsx
src/dialogs/common/import-database/instructions-section/instructions-section.tsx
src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts

fix(sql-script): change ddl to be sql-script

---

src/lib/data/import-metadata/scripts/clickhouse-script.ts
src/lib/data/import-metadata/scripts/cockroachdb-script.ts
src/lib/data/import-metadata/scripts/maria-script.ts
src/lib/data/import-metadata/scripts/mysql-script.ts
src/lib/data/import-metadata/scripts/oracle-script.ts
src/lib/data/import-metadata/scripts/postgres-script.ts
src/lib/data/import-metadata/scripts/sqlite-script.ts
src/lib/data/import-metadata/scripts/sqlserver-script.ts

Checked the queries on all dbs.

fix(import-database): remove the default fetch from import database

---

package-lock.json
src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field-modal/table-field-modal.tsx

fix: resolve unresponsive cursor and input glitches when editing field comments

---

src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field-modal/table-field-modal.tsx
vite.config.ts

feat(default value): add default value option to table field settings

---

src/components/toast/toaster.tsx
src/components/toast/use-toast.ts
src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/pages/editor-page/editor-page.tsx

fix: update multiple schemas toast to require user action

---

src/i18n/locales/ar.ts
src/i18n/locales/bn.ts
src/i18n/locales/de.ts
src/i18n/locales/en.ts
src/i18n/locales/es.ts
src/i18n/locales/fr.ts
src/i18n/locales/gu.ts
src/i18n/locales/hi.ts
src/i18n/locales/hr.ts
src/i18n/locales/id_ID.ts
src/i18n/locales/ja.ts
src/i18n/locales/ko_KR.ts
src/i18n/locales/mr.ts
src/i18n/locales/ne.ts
src/i18n/locales/pt_BR.ts
src/i18n/locales/ru.ts
src/i18n/locales/te.ts
src/i18n/locales/tr.ts
src/i18n/locales/uk.ts
src/i18n/locales/vi.ts
src/i18n/locales/zh_CN.ts
src/i18n/locales/zh_TW.ts
src/lib/data/data-types/data-types.ts
src/lib/data/export-metadata/export-per-type/mssql.ts
src/lib/data/export-metadata/export-per-type/mysql.ts
src/lib/data/export-metadata/export-per-type/sqlite.ts
src/lib/data/export-metadata/export-sql-script.ts
src/pages/editor-page/side-panel/tables-section/table-list/table-list-item/table-list-item-content/table-field/table-field-modal/table-field-modal.tsx

feat: add auto increment support for fields with database-specific export

---

src/pages/editor-page/canvas/area-node/area-node-context-menu.tsx
src/pages/editor-page/canvas/area-node/area-node.tsx
src/pages/editor-page/top-navbar/diagram-name.tsx

- Add right-click context menu for areas with edit/delete options
- Add pencil icon on hover for diagram name
- Add dynamic input width for diagram name
- Keep existing useClickAway behavior

feat: add area context menu and UI improvements
